spring.application.name=Pranaya

# Custom property pointing to your local folder
image.upload.dir=C:/pranaya/images/

# Disable caching so changes show up instantly on refresh
spring.thymeleaf.cache=false

#to retrieve files from google drive
google.drive.file.id=1DahRPvPRD5AL2NrAqvvMv5EjGDbLaIqE
google.drive.parent.folder.id=1v3xGvRydS-Q0ru_qCmtKjJuepicsap0S


# Tells springdoc to also include standard MVC @Controllers that return view templates
springdoc.show-actuator=false
springdoc.default-produces-media-type=text/html